#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.5.3
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'live-broadcomstartup.service' >/dev/null || true
	deb-systemd-invoke stop 'live-clock12or24.service' >/dev/null || true
	deb-systemd-invoke stop 'live-swap.service' >/dev/null || true
fi
# End automatically added section
